Modify Spatial Query Page
precision-sustainable-ag/drone-image-manipulation pull request #34
Opened 2024-11-22 22:13 UTC by nisarg210

- Split Page in 30:70 ratio
- Modify Map height to fit entire screen.
- Added Side Block.

2024-11-22 22:14 UTC, nisarg210 commented
New Page After Modifications.
![image](https://github.com/user-attachments/assets/6fd7823c-d30f-4cb8-b52b-21a683dd864c)

2024-11-25 18:33 UTC, jinamshah requested changes
* I've uploaded the gif for spatial query demo `src/assets/gifs/spatial_query_eg.gif`
* The left side and right side backgrounds are misaligned
![Screenshot 2024-11-25 at 1 28 49 PM](https://github.com/user-attachments/assets/5e3bcfaf-3a37-47fa-9224-d47d77dee991)
* move the date selection lower - leaves a lot of space at the bottom
* box drawn on the spatial query page doesn't change orientation if the map is rotated
* users should not be allowed to draw multiple boxes on the map

2024-11-25 18:41 UTC, jinamshah commented
++ needs rebase with base branch - https://github.com/precision-sustainable-ag/drone-image-manipulation/network

2024-11-26 10:58 UTC, akshat22 commented on src/pages/SpatialQuery/map.js
Current implementation has extra space in the left and right.

Refer to this file for page layout UI:
https://github.com/precision-sustainable-ag/drone-image-manipulation/blob/feature/mission-selection-changes/src/pages/orthomosaic_display/App.js

2024-11-26 11:48 UTC, akshat22 requested changes

2024-11-26 11:48 UTC, akshat22 commented on src/assets/gifs/spatial_query_eg.gif
delete this since you are using the video file

2024-11-26 11:48 UTC, akshat22 commented on src/pages/SpatialQuery/map.js
> +    console.log(map.getView().getProjection());
remove print

2024-11-26 14:19 UTC, nisarg210 commented on src/pages/SpatialQuery/map.js
According to figma design, we need extra padding on left and right both. As this is different from all other pages. @jinamshah also suggested to add more padding.

2024-11-26 16:28 UTC, jinamshah commented
* map draw box problem is still not fixed (see review above)
* reduce right and left padding to about 2.5% and add space between the two elements
* map gets cut by the footer

2024-11-29 21:43 UTC, jinamshah approved these changes

2024-11-29 21:44 UTC, merged